/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loja;

import entidades.*;
import dados.Catalogo;
import javax.swing.JOptionPane;

/**
 *
 * @author matheus
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
      private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {                                          
    String t = tfTipo.getText();
    String n = tfNome.getText();
    String b = tfBanda.getText();
    String au = tfAutor.getText();
    String a = tfAno.getText();
    String p = tfPreco.getText();
        
    int ano = Integer.parseInt(a);
    double preco = Double.parseDouble(p);
        
    if(t == "L" )
      Livro o = new Livro(n, au, ano, preco);
    else
      Disco o = new Disco(n, b, ano, preco);
      
    card.inserir(o);
    
    tfTipo.getText("");
    tfNome.setText("");
    tfAutor.setText("");
    tfBanda.setText("");
    tfAno.setText("");
    tfPreco.setText("");
    
    atLista.setText(o.getTipo() + " inserido: \n" + o);
  }                                         

    private void btListarTodosActionPerformed(java.awt.event.ActionEvent evt) {                                              
        //mostrar objetos na area de texto
        atLista.setText( card.listarTodos() );
    }                                             

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        //abrir arq p gravacao
        card.abreArquivoGravacao();

        //varrer obj arraylist gravando no arq
        card.gravarObjetos();

        //fechar arq gravacao
        card.fechaArquivoGravacao();

        JOptionPane.showMessageDialog(rootPane, "Gravados com sucesso!");
    }                                        

    private void btLerActionPerformed(java.awt.event.ActionEvent evt) {                                      
        //abrir arq p leitura
        card.abreArquivoLeitura();

        //ler objetos e preencher arraylist
        card.leRegistros();

        //fechar arq leitura
        card.fechaArquivoLeitura();

        JOptionPane.showMessageDialog(rootPane, "Lidos com sucesso!");
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }
    
Catalogo card = new Catalogo(); //obj que contem o ArrayList

private javax.swing.JLabel Ano;
  private javax.swing.JLabel Banda;
  private javax.swing.JLabel Nome;
  private javax.swing.JLabel Preco;
  private javax.swing.JTextArea atLista;
  private javax.swing.JButton btGravar;
  private javax.swing.JButton btInserir;
  private javax.swing.JButton btLer;
  private javax.swing.JButton btListarTodos;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JPanel painel1;
  private javax.swing.JTextField tfAno;
  private javax.swing.JTextField tfBanda;
  private javax.swing.JTextField tfNome;
  private javax.swing.JTextField tfPreco;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
